use std::collections::{HashMap, HashSet};

use crate::{entity::Entities, galaxy::living::character};

use super::Id;

// determines how much electronic equpment the building has & the power bill
struct Electronics {
    air_conditioning: u8,
}

pub struct Hotel {
    // how large the building is, affects:
    // - how many characters can this building fit
    // - property tax
    size: u8,

    // to show off how rich you are, affects:
    // - how much prestige is generated by the living family
    // - proportional increase in demand of furnitures
    glamour: u8,

    customers: HashSet<character::Id>,

    // workers
    concierge: HashSet<character::Id>,
}

pub struct Hotels {
    buildings: Entities<Hotel, Id>,

    cooks: HashMap<Id, HashSet<character::Id>>,

    // the hotel is electrified
    electronics: HashMap<Id, Electronics>,
}
