use std::collections::HashMap;

use crate::{entity::Entities, galaxy::living::dynasty};

use super::Id;

// determines how much electronic equpment the building has & the power bill
struct Electronics {
    air_conditioning: u8,
}

pub struct Residence {
    // how large the building is, affects:
    // - how many characters can this building fit
    // - property tax
    size: u8,

    // to show off how rich you are, affects:
    // - how much prestige is generated by the living family
    // - proportional increase in demand of furnitures
    glamour: u8,
}

pub struct Residences {
    buildings: Entities<Residence, Id>,

    // one family per house
    rented_by: HashMap<Id, dynasty::Id>,

    // the residence is electrified
    electronics: HashMap<Id, Electronics>,
}
